
spring:
  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口

    password: Genius123 # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/rvc2?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root

assistant:
  token:
    access-token-expire-time: 3600
    access-token-time-unit: SECONDS
    enable-refresh: true
  regex:
    pool:
      phone: ^1[3|4|5|7|8][0-9]{9}$#$
  service:
    id:
      snowflake:
        workerId: 1
        dataCenterId: 1
        register: register-redis
        startTime: 2023-12-05 00:00:00
    exception:
      handler:
        disables: springWebExceptionHandler
  mysql:
    query-group:
      feedback_list: fb_id,uid,title,type,status,comment_num,up_num,create_at
      feedback_detail: fb_id,uid,title,content,type,status,comment_num,up_num,create_at
  service-chain:
    serviceMap:
      string: stringNotEmpty->objectNotEmpty
      task: stringNotEmpty->objectNotEmpty->taskCheck
      taskException: stringNotEmpty->objectNotEmpty->taskCheck->Exception
      ignoreTaskException: stringNotEmpty->objectNotEmpty->taskCheck->Exception[ignore]
      getResult: stringNotEmpty->objectNotEmpty->returnMap
server:
  port: 16666
